[package]
name = "dec19x5"
edition = "2018"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]

[dependencies]
serde = { version = "1.0", optional = true }

[dev-dependencies]
serde_json = "1.0"
